app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager


from . import db

@login_manager.user_loader
def loader_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    pitchs = db.relationship('Pitch', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)



    def __repr__(self):
        return f'User {self.username}'


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    review = db.Column(db.String(255))

    def __repr__(self):
        return f'User{self.review}'


class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    head = db.Column(db.String(255))
    body = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, SelectField
from wtforms.validators import Required, Email, EqualTo
from ..models import User


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you', validators=[Required()])
    submit = SubmitField('submit')


class pitchIdea(FlaskForm):
    category = [('business', 'business'), ('science', 'science'),
                ('tech', 'tech'), ('interview', 'interview')]
    title = StringField('Pitch Title', validators=[Required()])
    pitch = TextAreaField('Tell us about your Idea', validators=[Required()])
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_mail import Mail

from flask_uploads import UploadSet, configure_uploads, IMAGES


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)
mail = Mail()



def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    # configure UploadSet
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main

from .forms import pitchIdea,UpdateProfile
from .. import db, photos
from flask_login import login_required
from ..models import User,Pitch,Category

@main.route('/',methods=['GET','POST'])

def index():

    form=pitchIdea()


    pitch=Pitch.query.all()
    if form.validate_on_submit():
        title=form.title.data
        body=form.pitch.data

        new_pitch=Pitch(head=title,body=body)
        db.session.add(new_pitch)
        db.session.commit()

    return render_template('index.html',pitch=pitch,form=form)

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()
    form=UpdateProfile()
    if user is None:
        abort(404)


    if form.validate_on_submit():
        User.bio=form.bio.data
        db.session.add(user)
        db.session.commit()

    return render_template('profile/update.html',user=user.username,form=form)


@main.route('/user/<uname>/update',methods=['GET','POST'])
@login_required
def update_profile(uname):
    user=User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    form=UpdateProfile()

    if form.validate_on_submit():
        user.bio=form.bio.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username,form=form))

    return render_template('profile/update.html',form=form,user=user)


@main.route('/user/<uname>/update/pic',methods=['POST'])
@login_required
def  update_pic(uname):
    user=User.query.filter_by(username=uname).first()
    if 'photos' in request.files:
        filename=photos.save(request.files['photo'])
        path=f'photos/{filename}'
        user.profile_pic_path=path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block content%}
    <!-- Navbar block  -->
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}
{%endblock%}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{%block content%} {%import 'bootstrap/wtf.html' as wtf%}
<div class="container">
  <div class="row">
    <div class="col-md-8 col-sm-7 col-xs-6">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Pitch Title</th>
            <th>Pitch Idea</th>
            <th>time</th>
            <th>Reviews</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            {{ macro.display_pitch(pitch)}}
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-4 col-sm-5 col-xs-6">
        {{wtf.quick_form(form)}}
    </div>
  </div>
</div>
{%endblock content%}

app/templates/macros.html
{% macro display_pitch(pitch_list) %}

        {% for pitch in pitch_list %}
        <tr>
        <th scope="row"></th>
            <td>{{pitch.head}}</td>
            <td>{{pitch.body}}</td>
            <td>{{pitch.time}}</td>
            <td><a href="/pitch/{{pitch.id}}">Review</a></td>

        </tr>
        {% endfor %}


{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="/"> Pitches </a>
       </div>
       <div class="navbar-collapse collapse">
           <ul class="nav navbar-nav">
               <li><a href="/">Home</a></li>
               <ul class="nav navbar-nav navbar-right">
                   {% if current_user.is_authenticated %}
                       <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                       <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                   {% else %}
                        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                        <li><a href="{{url_for('auth.signup')}}">Signup</a></li>
                   {%endif%}
               </ul>
           </ul>


    </div>

  </div>

</div>

app/templates/profile/profile.html
{%block content%}
<div class="container">
  <div class="row">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    1{% endif %}
    <div class="col-md-4">
      <h3>{{user.username| capitalize}}</h3>

      <!--  User bio -->
      {%if user.bio%}
      <p>{{user.bio}}</p>
      {%else%}
      <p>{{user.bio| has no bio}}</p>
      {%endif%}
    </div>

    <div class="col-md-4">
      <!--profile photo-->
      {%if user.profile_pic_path%}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profie picture</p>
      {%endif%}
    </div>
    <div class="col-md-4">
      {% if user.profile_pic_path %}

      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

      {%else%}
      <p>No profile picture</p>

      {% endif %}

      {% if user == current_user %}
      <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

        <input type="file" name="photo" class="form-control" required>
        <input type="submit">

        {% endif %}
    </div>
  </div>
</div>
{%endblock%}